INSERT INTO doctor (
                       id,
                       doctor_name,
                       middle_name,
                       last_name,
                       age,
                       sex,
                       cpf,
                       name_mother,
                       name_father,
                       email,
                       crm,
                       specialty,
                       id_shift,
                       street_address,
                       number_address,
                       neighbourhood_address,
                       city_address,
                       state_address,
                       country_address,
                       zipcode_address
                   )
                   VALUES (
                       1,
                       'Robin',
                       '',
                       'Pereira',
                       25,
                       'MAS',
                       '916.149.670-75',
                       'Robina Pereira',
                       'Robin Wood',
                       'robin_batata123@yahoo.com',
                       'CRM/SC 698547',
                       'Oftalmologista',
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL
                   );

INSERT INTO doctor (
                       id,
                       doctor_name,
                       middle_name,
                       last_name,
                       age,
                       sex,
                       cpf,
                       name_mother,
                       name_father,
                       email,
                       crm,
                       specialty,
                       id_shift,
                       street_address,
                       number_address,
                       neighbourhood_address,
                       city_address,
                       state_address,
                       country_address,
                       zipcode_address
                   )
                   VALUES (
                       2,
                       'Clark',
                       '',
                       'Kent',
                       35,
                       'MAS',
                       '023.236.896-45',
                       'Martha Kent',
                       'Jonathan Kent',
                       'clarkinhi56@gmail.com',
                       'CRM/SC 698512',
                       'Oftalmologista',
                       1,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL
                   );

INSERT INTO doctor (
                       id,
                       doctor_name,
                       middle_name,
                       last_name,
                       age,
                       sex,
                       cpf,
                       name_mother,
                       name_father,
                       email,
                       crm,
                       specialty,
                       id_shift,
                       street_address,
                       number_address,
                       neighbourhood_address,
                       city_address,
                       state_address,
                       country_address,
                       zipcode_address
                   )
                   VALUES (
                       3,
                       'Clark',
                       '',
                       'Kent',
                       35,
                       'MAS',
                       '023.236.896-44',
                       'Martha Kent',
                       'Jonathan Kent',
                       'clarkinho56@gmail.com',
                       'CRM/SC 698513',
                       'Oftalmologista',
                       2,
                       'Rua dos El',
                       '1569',
                       'Bairro dos Kent',
                       'Smallville',
                       'EL',
                       'Kal el',
                       '56600-006'
                   );

INSERT INTO doctor (
                       id,
                       doctor_name,
                       middle_name,
                       last_name,
                       age,
                       sex,
                       cpf,
                       name_mother,
                       name_father,
                       email,
                       crm,
                       specialty,
                       id_shift,
                       street_address,
                       number_address,
                       neighbourhood_address,
                       city_address,
                       state_address,
                       country_address,
                       zipcode_address
                   )
                   VALUES (
                       4,
                       'Diana',
                       '',
                       'Prince',
                       35,
                       'FEM',
                       '897.123.489-63',
                       'Hipolita Prince',
                       'Zeus Prince',
                       'diana_prince@gmail.com',
                       'CRM/SC 123489',
                       'Neurologista',
                       2,
                       'Av das Pedras',
                       '78',
                       'Bairro do Olimpo',
                       'Olimpo',
                       'OL',
                       'Olimpk',
                       '89600-000'
                   );
