INSERT INTO doctor (
                       id,
                       doctor_name,
                       middle_name,
                       last_name,
                       age,
                       sex,
                       cpf,
                       name_mother,
                       name_father,
                       email,
                       crm,
                       specialty,
                       id_shift,
                       street_address,
                       number_address,
                       neighbourhood_address,
                       city_address,
                       state_address,
                       country_address,
                       zipcode_address
                   )
                   VALUES (
                       1,
                       'Robin',
                       '',
                       'Pereira',
                       25,
                       'MAS',
                       '916.149.670-75',
                       'Robina Pereira',
                       'Robin Wood',
                       'robin_batata123@yahoo.com',
                       'CRM/SC 698547',
                       'Oftalmologista',
                       1,
                       "Rua Wood",
                       "100",
                       "Bairro Wood",
                       "Imbituba",
                       "SC",
                       "Brasil",
                       "88780-000"
                   );

INSERT INTO doctor (
                       doctor_name,
                       middle_name,
                       last_name,
                       age,
                       sex,
                       cpf,
                       name_mother,
                       name_father,
                       email,
                       crm,
                       specialty,
                       id_shift,
                       street_address,
                       number_address,
                       neighbourhood_address,
                       city_address,
                       state_address,
                       country_address,
                       zipcode_address
                   )
                   VALUES (
                       'Clark',
                       '',
                       'Kent',
                       35,
                       'MAS',
                       '023.236.896-45',
                       'Martha Kent',
                       'Jonathan Kent',
                       'clarkinhi56@gmail.com',
                       'CRM/SC 698512',
                       'Oftalmologista',
                       1,
                       "Rua dos El",
                       "1569",
                       "Clarklandia",
                       "Smallville",
                       "SC",
                       "Brasil",
                       "56600-006"
                   );


INSERT INTO doctor (
                       doctor_name,
                       middle_name,
                       last_name,
                       age,
                       sex,
                       cpf,
                       name_mother,
                       name_father,
                       email,
                       crm,
                       specialty,
                       id_shift,
                       street_address,
                       number_address,
                       neighbourhood_address,
                       city_address,
                       state_address,
                       country_address,
                       zipcode_address
                   )
                   VALUES (
                       'Diana',
                       '',
                       'Prince',
                       35,
                       'FEM',
                       '897.123.489-63',
                       'Hipolita Prince',
                       'Zeus Prince',
                       'diana_prince@gmail.com',
                       'CRM/SC 123489',
                       'Neurologista',
                       2,
                       'Av das Pedras',
                       '78',
                       'Bairro do Olimpo',
                       'Olimpo',
                       'OL',
                       'Olimpk',
                       '89600-000'
                   );
                   
select * from doctor;
