NSERT INTO patient (patient_name,
                     middle_name,
                     last_name,
                     age,
                     sex,
                     cpf,
                     name_mother,
                     name_father,
                     email,
                     patology,
                     street_address,
                     number_address,
                     neighbourhood_address,
                     city_address,
                     state_address,
                     country_address
                    )
                    VALUES 
(
                    /* insert Steve Rogers */
                        "Steve",
                        "Grant",
                        "Rogers",
                        29,
                        'MAS',
                        "897.123.489-63",
                        "Sarah Rogers",
                        "Joseph Rogers",
                        "steve.rogers@yahoo.com",
                        "Dor nos olhos",
                        "Av das Americas",
                        "407",
                        "Bairro Stevinho",
                        "Stevenlandia",
                        "SR",
                        "Rogerlandia");
                        
                        INSERT INTO patient (patient_name,
                     middle_name,
                     last_name,
                     age,
                     sex,
                     cpf,
                     name_mother,
                     name_father,
                     email,
                     patology,
                     street_address,
                     number_address,
                     neighbourhood_address,
                     city_address,
                     state_address,
                     country_address
                    )
                    values
                    ("Peter",
                        "",
                        "Parker",
                        21,
                        'MAS',
                        "023.156.159-62",
                        "Mary Parker",
                        "Richard Parker",
                        "peter.parker@gmail.com",
                        "Limpeza dentária",
                        "Rua dos Limoeiros",
                        "569",
                        "Bairro Limonada",
                        "Peterland",
                        "PP",
                        "Parkerland"
                    );
                    /* insert Tonynho */ 
                   INSERT INTO patient (patient_name,
                     middle_name,
                     last_name,
                     age,
                     sex,
                     cpf,
                     name_mother,
                     name_father,
                     email,
                     patology,
                     street_address,
                     number_address,
                     neighbourhood_address,
                     city_address,
                     state_address,
                     country_address
                    )values (
                        "Anthony",
                        "Edward",
                        "Stark",
                        58,
                        'MAS',
                        "123.563.159-85", 
                        "Maria Stark", 
                        "Howard Stark",
                        "iron_man@gmail.com",
                        "Troca de lentes",
                        "Av da Fé",
                        "123",
                        "Bairro Sexta-Feira",
                        "Tonylandia",
                        "TS",
                        "Starkland"
                    );

INSERT INTO patient (patient_name,
                     middle_name,
                     last_name,
                     age,
                     sex,
                     cpf,
                     name_mother,
                     name_father,
                     email,
                     patology,
                     street_address,
                     number_address,
                     neighbourhood_address,
                     city_address,
                     state_address,
                     country_address
                    )
                    values
                    ("Natasha",
                        "",
                        "Romanoff",
                        32,
                        'FEM',
                        "123.456.789-96",
                        "Melina Vostokoff",
                        "Alexei Shostakov",
                        "black_widowahoo.@gmail.com",
                        "Dores fortes de cabeça",
                        "Rua das Flores",
                        "99",
                        "Kimlobo",
                        "Smallville",
                        "SC",
                        "Roma"
                    );
                    /* insert Tonynho */ 
                INSERT INTO patient (patient_name,
                     middle_name,
                     last_name,
                     age,
                     sex,
                     cpf,
                     name_mother,
                     name_father,
                     email,
                     patology,
                     street_address,
                     number_address,
                     neighbourhood_address,
                     city_address,
                     state_address,
                     country_address
                    )   
                    values
 (
                        "Thor",
                        "",
                        "Odinson",
                        33,
                        'MAS',
                        "023.563.698.96", 
                        "Joro", 
                        "Odin",
                        "thunder_god@gmail.com",
                        "Enxaqueca",
                        "Av Mjolnir",
                        "1903",
                        "Bairro Sexta-Feira",
                        "Joacaba",
                        "SC",
                        "BR"
                    );
                    
INSERT INTO patient (patient_name,
                     middle_name,
                     last_name,
                     age,
                     sex,
                     cpf,
                     name_mother,
                     name_father,
                     email,
                     patology,
                     street_address,
                     number_address,
                     neighbourhood_address,
                     city_address,
                     state_address,
                     country_address
                    )   
                    values(
                        "Wanda",
                        "",
                        "Maximoff",
                        28,
                        'FEM',
                       "023.102.558-85", 
                       "Magda Maximoff",
                       "Erik Lehnsherr",
                       "scarlet_witch@gmail.com",
                        "Exames de rotina",
                        "Av Vision",
                        "456",
                        "Bairro Escarlate",
                        "Joacaba",
                        "WM",
                        "Escarlatelandia"
                    );
                    

                    
select * from patient;